name: Pruebas Automáticas

on:
  push:
    branches:
      - master  # Usa 'master' si es tu rama principal
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Instalar dependencias
        run: |
          poetry install --no-root

      - name: Ejecutar pruebas
        run: |
          poetry run pytest tests/test_upload.py -v

      - name: Subir reporte de cobertura a Codecov
        uses: codecov/codecov-action@v3